@startuml mapadasaude
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

System_Boundary(agregador, "Base project (agregador)") {
    Container(postgres, "Postgres", "Postgres")
    Container(baseproject, "Mapas Base Project", "Nginx, PHP FPM")


    System(plugins, "Plugins mapa da saúde") {
        Container(pluginLocationStateCity, "Plugin LocationStateCity", "Plugin")
        Container(pluginEvaluationMethodHomolog, "Plugin EvaluationMethodHomolog", "Plugin")
        Container(pluginEvaluationMethodTechnicalNa, "Plugin EvaluationMethodTechnicalNa", "Plugin")
        Container(pluginPDFReport, "Plugin PDFReport", "Plugin")
        Container(SealCertified, "Plugin SealCertified", "Plugin")
        Container(EditarInscricao, "Plugin EditarInscricao", "Plugin")
    }

    System(temas, "Temas") {
        Container(temasaude, "Tema Saúde", "Tema Saúde", "branch refatoração")
    }

    System_Boundary(mapadasaude, "Mapa da saúde") {
        System(mapadasaudecore, "Mapa da saúde versão 5.2.2", "branch MERGE ESP 5.2.2")
        System(opauthkeycloak, "Opauth Keycloak", "Integração mapas e keycloak")
    }
}

Rel(plugins, baseproject, "Plugins integrados com git submodules e mapeados pelo volume", "git, docker");
Rel(temasaude, baseproject, "Tema integrados com git submodules e mapeados pelo volume", "git, docker");
Rel(mapadasaudecore, baseproject, "Core mapa da saúde integrados com git submodules e mapeados pelo volume", "git, docker")
Rel(baseproject, postgres, "Acesso ao banco de dados", "Doctrine/ORM")
Rel(opauthkeycloak, mapadasaudecore, "Integração via Composer", "Composer")

@enduml